// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRCScJYFTe4L8MnhBA4tTQcV-83GOuO_0',
    appId: '1:327506985961:web:e30e26a34a0b1559bcc178',
    messagingSenderId: '327506985961',
    projectId: 'ma-voix-app',
    authDomain: 'ma-voix-app.firebaseapp.com',
    storageBucket: 'ma-voix-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOACXhsCuqTKLrbfaUNlzZ8W7yOKuLr4',
    appId: '1:327506985961:android:879a1cad35ce59cfbcc178',
    messagingSenderId: '327506985961',
    projectId: 'ma-voix-app',
    storageBucket: 'ma-voix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCitDT6zy9UYvulW556jv7u1MnmD5nOfds',
    appId: '1:327506985961:ios:2d42701e81343835bcc178',
    messagingSenderId: '327506985961',
    projectId: 'ma-voix-app',
    storageBucket: 'ma-voix-app.firebasestorage.app',
    iosBundleId: 'com.wilkeo.maVoix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCitDT6zy9UYvulW556jv7u1MnmD5nOfds',
    appId: '1:327506985961:ios:2d42701e81343835bcc178',
    messagingSenderId: '327506985961',
    projectId: 'ma-voix-app',
    storageBucket: 'ma-voix-app.firebasestorage.app',
    iosBundleId: 'com.wilkeo.maVoix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRCScJYFTe4L8MnhBA4tTQcV-83GOuO_0',
    appId: '1:327506985961:web:ede68867f34a12bdbcc178',
    messagingSenderId: '327506985961',
    projectId: 'ma-voix-app',
    authDomain: 'ma-voix-app.firebaseapp.com',
    storageBucket: 'ma-voix-app.firebasestorage.app',
  );

}